### ISSUE TITLE
Unfriendly error message from `liff.scanCodeV2()` on old devices

### ISSUE THREAD

**Issue by cola119** [line/liff-playground#18]
The error message shown in `liff.scanCodeV2()` section when the API is called on the old version device is inaccurate and leads to misunderstanding.

For example, `liff.scanCodeV2()` works on iOS 14.3 or later, and LINE version 11.7.0 or later ([doc](https://developers.line.biz/en/reference/liff/#scan-code-v2)), but when it is called iOS 14.2.1, `No permission for liff.scanCodeV2()` is shown. This message is inaccurate and the correct one is something like `This API is not available on this device.` 
<img src="https://user-images.githubusercontent.com/22386678/211803727-e402090b-01db-4449-a516-8a46f9e3d411.png" width="300px" />

I'm not sure if this error message is from LIFF SDK or the playground but if it is on the playground side problem, the error handler has room for improvement.

**Comment by cola119** [comment]
@LeeChSien Do you have a full picture of it?

**Comment by LeeChSien** [comment]
@cola119 

https://github.com/line/liff-playground/blob/6d7c9dd6a6d34c352f7f92e06fedbb94685e7eef/src/components/Snippet.tsx#L63-L65

As you can see, this error message is from LIFF SDK itself.
You guys can probably replace it with a new error message (feel free to use `liff.i18n`).

**Comment by cola119** [comment]
Thank you @LeeChSien! We are planning to improve error messages at a version!
